### PR TITLE
Make util imports relative in /models

### PR DESCRIPTION
**Pull request by roya0045**
Greetings,

This is just a small tweak to allow importing components without error about util. I had to tweak this to use the model components when cloning the dir.

Thanks for the great work!

### CODE REVIEW

**Comment by roya0045** [comment]
I forgot that limitation and the fact that the relative imports work from the running file... I'll try something else.

**Comment by fmassa** [comment]
Hi,

Such an approach would need to have DETR packaged as a library, which we decided not to do because it would force us to have many more restrictions wrt API.

**Comment by roya0045** [comment]
@fmassa Thanks for the reply. TBH I'm not sure what kind of restriction we are talking about here, though I feel like simple reorganising the files might make it more workable if need be. I'll keep my fork with the .. as its the simplest way I found to import things in colab as I'm trying to combine the faster rcnn approach (for the scale independence) and the transformer part at the bottom of the model. Though its more of a hobby/prototype.

I feel like having access to the full components that you have made is better than having to remake them from scratch for any implementation that wants to use this novel approach.

**Comment by fmassa** [comment]
@roya0045 you can import the files you need if you execute your script from the root folder of detr.
So if you want to use say Detectron2 with DETR, you can, as long as you run from the root folder of DETR.

**Comment by roya0045** [comment]
@fmassa Yeah with the .. , it works on colab, its what matters for now.

**Pull request closed without merging**
