### PR TITLE
Add unittest of libtorch tracing

### PR DESCRIPTION
**Pull request by zhiqwang**
As a subsequent PR of #238 

cc @fmassa

### CODE REVIEW

**Comment by fmassa** [comment]
Awesome, thanks for the PR with the failing test case!

Here is one guess on what's happening: because we mark `_onnx_nested_tensor_from_tensor_list` as `unused`, torchscript doesn't introspect  beyond its type annotation to infer the return types. As such, because no type annotations are provided for the return type of `_onnx_nested_tensor_from_tensor_list`, it defaults to `Tensor`.

One way to test if this hypothesis is correct is to add a return type annotation to `_onnx_nested_tensor_from_tensor_list`, something like
```python
def _onnx_nested_tensor_from_tensor_list(tensor_list: List[Tensor]) -> 'NestedTensor':
```

Could you try that?

**Comment by zhiqwang** [comment]
Hi @fmassa It will raise a ValueError: Unkuown type annotation: 'NestedTensor'

It's a user-define Type, but I don't know to declare it in right ways, I have push my changes, you can check the outputs of the CI.

**Comment by fmassa** [comment]
@zhiqwang moving `NestedTensor` to before the function definition (say putting it in line 283 before `nested_tensor_from_tensor_list`) and changing the signature to
```python
def _onnx_nested_tensor_from_tensor_list(tensor_list: List[Tensor]) -> NestedTensor:
```
solves the problem for me. Can you make the changes, this should fix CI.

**Comment by zhiqwang** [comment]
Hi @fmassa , It works!

**Review by fmassa — APPROVED** [review]
Thanks a lot!

**Pull request merged**
